services:
  prefect-server:
    image: prefecthq/prefect:2.13-python3.9
    command: prefect orion start --host 0.0.0.0
    ports:
      - "4200:4200"      # Orion UI
    restart: unless-stopped

  prefect-agent:
    image: prefecthq/prefect:2.13-python3.9
    depends_on:
      - prefect-server
    command: prefect agent start --work-queue default
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./flows:/app/flows
    environment:
      PREFECT_API_URL: http://prefect-server:4200/api
    restart: unless-stopped

  news_scraper:
    build: .
    depends_on:
      - prefect-agent
    volumes:
      - ./data:/app/data
    command: ["prefect", "deployment", "run", "news_scraper/scrape_news-deployment"]
    restart: "no"
