version: '3'

services:
  prefect-server:
    image: prefecthq/prefect:latest
    environment:
      - PREFECT_API_URL=http://0.0.0.0:4200/api
      - PREFECT_DATABASE_URL=postgresql://user:password@postgres:5432/prefect
    ports:
      - "4200:4200"
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: prefect
    volumes:
      - postgres_data:/var/lib/postgresql/data

  prefect-agent:
    image: prefecthq/prefect:latest
    command: prefect agent start
    environment:
      - PREFECT_API_URL=http://prefect-server:4200/api
    depends_on:
      - prefect-server

volumes:
  postgres_data:
